name: Deploy Thumblify app to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }} # VPS public IP
          username: ubuntu
          key: ${{ secrets.SSH_KEY }} # private key
          script: |
            # Fix git safe directory issue
            git config --global --add safe.directory /home/ubuntu/AI_Thumbnail_Generator

            cd /home/ubuntu/AI_Thumbnail_Generator

            echo "Pulling latest code"
            git pull origin main

            echo "Building Docker containers"
            sudo docker compose build

            echo "Starting containers"
            sudo docker compose up -d

            echo "Deployment completed successfully"
